language: generic

include:
  - os: linux
    addons:
      apt:
        packages:
          - "python3"
          - "python3-pip"

sudo: required
dist: xenial

before-install:
  - pip install --upgrade pip

install:
  - pip install -r requirements.txt
  
