language: generic

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"

before_install:
 - pip3 install --upgrade pip

install:
  - pip3 install -r requirements.txt
  - pip3 install pytest

script:
  - python3 tweet.py 