language: python
python:
  - "2.7"
  - "3.4"
virtualenv:
  system_site_packages: true

include:
  - os: linux
    addons:
      update: true
      sources:
          - ubuntu-toolchain-r-test
        packages:
          - python-tk 

sudo: required
dist: xenial

before-install:
  - pip install --upgrade pip

install: pip install --user -r requirements.txt

script: python tweet.py
  
