language: python
python:
  - "2.7"
  - "3.4"
virtualenv:
  system_site_packages: true

sudo: required
dist: xenial

before_install:
  - sudo apt-get install python-tk
  - pip install --upgrade pip

install: pip install --user -r requirements.txt

script:
  - echo $TRAVIS_BUILD_DIR 
  - python tweet.py
  
